# syntax=docker/dockerfile:1
FROM scratch
--------------------------------------------------------------------------------
# syntax=docker/dockerfile:1
# Copyright (c) 2026 Joseph Hale
# SPDX-License-Identifier: MPL-2.0

FROM scratch
